### ISSUE TITLE
Make role work with staging and snapshot repositories

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/ansible-role-perfsonar-installer#3]
We changed staging and snapshot repositories URL with the last release.  We should update comments and documentation to reflect that in this role.

**Comment by igarny** [comment]
we need to check with Andy @arlake228 as it seems the procedure for **nightly** is different ... (see Slack-General 07.07.2020)
Meaning prior install of the stable repository, before the nightly may lead to package conflicts. Currently this is the case.
Or we need to introduce lists of repositories, which need to be installed, when one is selected.

Most likely we do not want to put much effort here.

EDIT:
Something doesn't seem right and it might be my TV set, that's broken, but mixing repositories gave me failures

**Comment by laeti-tia** [comment]
This has been fixed in https://github.com/perfsonar/ansible-role-perfsonar-installer/commit/a87f791753b8bf3d2a42d2fcfaa8ff10fc26c882
